"""empty message

Revision ID: a7397c24a8ed
Revises: dd76e8dbb0b0
Create Date: 2020-01-13 17:40:14.663429

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7397c24a8ed'
down_revision = 'dd76e8dbb0b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workout', sa.Column('name', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workout', 'name')
    # ### end Alembic commands ###
