"""empty message

Revision ID: beadefe45a2e
Revises: a7397c24a8ed
Create Date: 2020-01-14 09:35:55.427150

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'beadefe45a2e'
down_revision = 'a7397c24a8ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_workout_owner', table_name='workout')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_workout_owner', 'workout', ['owner'], unique=1)
    # ### end Alembic commands ###
